INSERT INTO event_type VALUES('clean_sheet','Goalkeeper',4);
INSERT INTO event_type VALUES('clean_sheet','Defender',4);
INSERT INTO event_type VALUES('clean_sheet','Midfielder',1);
INSERT INTO event_type VALUES('red_card','Goalkeeper',-2);
INSERT INTO event_type VALUES('red_card','Defender',-2);
INSERT INTO event_type VALUES('red_card','Midfielder',-2);
INSERT INTO event_type VALUES('red_card','Forward',-2);
INSERT INTO event_type VALUES('yellow_card','Goalkeeper',-1);
INSERT INTO event_type VALUES('yellow_card','Defender',-1);
INSERT INTO event_type VALUES('yellow_card','Midfielder',-1);
INSERT INTO event_type VALUES('yellow_card','Forward',-1);
INSERT INTO event_type VALUES('goal','Goalkeeper',8);
INSERT INTO event_type VALUES('goal','Defender',6);
INSERT INTO event_type VALUES('goal','Midfielder', 5);
INSERT INTO event_type VALUES('goal','Forward',4);
INSERT INTO event_type VALUES('assist','Goalkeeper',5);
INSERT INTO event_type VALUES('assist','Defender',4);
INSERT INTO event_type VALUES('assist','Midfielder', 2);
INSERT INTO event_type VALUES('assist','Forward',2);