INSERT INTO team VALUES('Arsenal', NULL, 'Premier League', 'ARS');
INSERT INTO team VALUES('Liverpool', NULL, 'Premier League', 'LIV');
INSERT INTO team VALUES('Leicester City', NULL, 'Premier League', 'LEI');
INSERT INTO team VALUES('Chelsea', NULL, 'Premier League','CHE');
INSERT INTO team VALUES('Manchester City', NULL, 'Premier League', 'MCI');
INSERT INTO team VALUES('Sheffield United', NULL, 'Premier League', 'SHU');
INSERT INTO team VALUES('Manchester United', NULL, 'Premier League', 'MUN');
INSERT INTO team VALUES('Wolverhampton Wanderers', NULL, 'Premier League', 'WOL');
INSERT INTO team VALUES('Bournemouth ', NULL, 'Premier League', 'BOU');
INSERT INTO team VALUES('Burnley', NULL, 'Premier League', 'BUR');
INSERT INTO team VALUES('Brighton and Hove Albion', NULL, 'Premier League', 'BHA');
INSERT INTO team VALUES('Crystal Palace', NULL, 'Premier League', 'CRY');
INSERT INTO team VALUES('Newcastle United', NULL, 'Premier League', 'NEW');
INSERT INTO team VALUES('Tottenham Hotspur', NULL, 'Premier League', 'TOT');
INSERT INTO team VALUES('Everton', NULL, 'Premier League', 'EVE');
INSERT INTO team VALUES('West Ham United', NULL, 'Premier League', 'WHU');
INSERT INTO team VALUES('Aston Villa', NULL, 'Premier League', 'AVL');
INSERT INTO team VALUES('Watford', NULL, 'Premier League', 'WAT');
INSERT INTO team VALUES('Southampton', NULL, 'Premier League', 'SOU');
INSERT INTO team VALUES('Norwich City', NULL, 'Premier League', 'NOR');